# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FccaXYdir0 <- function(Lx, Lp, LPhi, resp, l1, l2, cv = 1L) {
    .Call('flars_FccaXYdir0', PACKAGE = 'flars', Lx, Lp, LPhi, resp, l1, l2, cv)
}

FccaXYdir <- function(Lx, Lp, LPhi, resp, l1, l2, cv = 1L) {
    .Call('flars_FccaXYdir', PACKAGE = 'flars', Lx, Lp, LPhi, resp, l1, l2, cv)
}

